[build.environment]
NPM_FLAGS="--version"

[build]
command = "npx pnpm@6 install --store-dir=.pnpm --frozen-lockfile && npx pnpm@6 build"

[[plugins]]
package = "netlify-plugin-cache"
  [plugins.inputs]
  paths = [".pnpm"]
